### ISSUE TITLE
Proposal: Dictionary equivalency checks should not complain about extraneous keys

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#1000]
Just like comparing an object to an anonymous type using `Should().BeEquivalentTo()`, comparing two dictionaries like this should not care about extra keys in the original dictionary. 

This redefines what _equivalent_ means for dictionaries: 

> If the actual dictionary contains all keys defined in the expected dictionary and its values are equivalent, then the dictionaries are equivalent.

@jnyrup ?

**Comment by jnyrup** [comment]
I think `BeEquivalentTo` should be driven by the *shape* of the expectation.

If you look at a dictionary as a collection of key-value-pairs, which is what it implements in terms of `ICollection<KeyValuePair<TKey, TValue>>`, I don't think it makes sense.

If you look at a dictionary as a dynamic structure, where you use keys instead of defining properties, then it *could* make sense to me, as the keys would then define the shape of your instance.
It would also be a very hacky and terrible misuse of dictionaries.
Sounds like a scripting language where you have no compile-time guarantees that a property on an instance exists.

I look at dictionaries as a collection, so currently I don't like it.

**Comment by dennisdoomen** [comment]
So to make sure I understand you correctly, you mean to say that two dictionaries are equivalent if they contain the same keys with values that are equivalent?

**Comment by jnyrup** [comment]
Yes.

**Comment by dennisdoomen** [comment]
Alright. Closing this proposal.
