### ISSUE TITLE
Abstract time away from ExecutionTime

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1085]
#1076 abstracted time (`Wait`, `Delay` and more) to make testing `DelegationAssertions` reliable.

We should do the same for `ExecutionTime`.

**Comment by jnyrup** [comment]
I'm giving this a try here https://github.com/jnyrup/fluentassertions/tree/ExecutionTime
I could use an extra pair of eyes as it's not working yet.

**Comment by Evangelink** [comment]
@jnyrup I suspect that the problem is coming from the [line 45](https://github.com/jnyrup/fluentassertions/commit/796982b1f1e7dc01491ce72ed7798096128e718d#diff-b92251b31975b253d34fed16bed41833R45) when executing `!execution.Wait(rate);`.

If you try to debug the test described [here](https://github.com/jnyrup/fluentassertions/commit/796982b1f1e7dc01491ce72ed7798096128e718d#diff-dd0f96bbe45e01b1feafc897a60a299dR437), you will end up with the following workflow:
1. Set result of the `delayTask` to `true`
2. Fake wait for 100ms (time given in the `BeGreaterThan`)
3. Return `true`, result that was set in #1
4. `isRunning` is now `false` so we stop the loop
5. We execute the assertion with the currently elapsed time
6. We fake sleep for 200ms
7. Test fails because 100ms not strictly greater than 100ms

**Comment by Serg046** [comment]
Clock doesn't have `Wait(task, timeout)` anymore so we cannot set sleeping time automatically as we do it with Delay/DelayAsync

**Comment by jnyrup** [comment]
@Serg046 If cracking the case involves re-introducing members on Clock that's fine.
The whole `IClock/Clock` mechanism was introduced solely to be able to abstract time for our unit tests.

**Comment by jnyrup** [comment]
`When_the_execution_time_of_a_member_is_close_to_a_limit_it_should_not_throw` failed in https://ci.appveyor.com/project/dennisdoomen/fluentassertions/builds/40080954.

```cs
Action act = () => subject.ExecutionTimeOf(s => s.Sleep(210)).Should().BeCloseTo(200.Milliseconds(),
    150.Milliseconds());
```

I read from #1620 that you decided to keep using a real `StopWatch` for all remaining tests - I assume that's to keep tests close to the actual executed paths?

It would be convenient to get rid of all remaining calls to `Thread.Sleep`, but it would either:
* Leave `StopwatchTimer` untested, or 
* Test directly on the internals of `StopwatchTimer`, which I know usually want to avoid.

Would you prefer if I only made the same fix to `When_the_execution_time_of_a_member_is_close_to_a_limit_it_should_not_throw` as in #1620?

**Comment by dennisdoomen** [comment]
> I read from #1620 that you decided to keep using a real `StopWatch` for all remaining tests - I assume that's to keep tests close to the actual executed paths?

Correct.

> Would you prefer if I only made the same fix to `When_the_execution_time_of_a_member_is_close_to_a_limit_it_should_not_throw` as in #1620?

I think we should only fix the ones that tend to be unstable.
