### ISSUE TITLE
Returning the value after validation

### ISSUE THREAD

**Issue by CaseyPlummer** [fluentassertions/fluentassertions#1148]
This is an idea/suggestion.

It would be nice if to have a `.Value()` method to just get the value after the validation chain is done.

For example, writing a property with strong validation on the setter:

```c#
public Product Product
{
    get => _product;
    private set => _product = value.Should().NotBeNull().Value();
}
```

**Comment by CaseyPlummer** [comment]
Never mind, I think this is covered in the .Subject property.

**Comment by jnyrup** [comment]
For assertions returning `AndConstraint` or `AndWhichConstraint` the `Subject` property sounds like what you seek.
Unfortunately there are a few assertions, that returns `void` instead of a type.

For types directly supported by Fluent Assertions the type of `Subject` should be the same as the type of the subject, that is `"hello".Should().NotBeNull()` returns a `string`.

For types not supported directly `Should(this object)` is used, which removes the compile time type knowledge about the subject.
One workaround could be to use `As<T>` to cast it back again.
`myType.Should().NotBeNull().As<MyType>()`.

**Comment by CaseyPlummer** [comment]
Thank you for the clarification. I'll leave it to you as to whether you want to re-open this issue for tracking/ToDo purposes. Thanks for the great library.
