### ISSUE TITLE
Request for DateTime extension method to produce DateTimeOffset

### ISSUE THREAD

**Issue by gregveres** [fluentassertions/fluentassertions#1192]
### Description

I really like the fluent way of creating a DateTime. But I use DateTimeOffset all over my code to better handle timezones. There doesn't seem to be a fluent way to create a DateTimeOffset. 

The best I have come up with is:

`new DateTimeOffset(1.November(2019).As(10,0), TimeSpan.FromHours(-5));
`
It would be really nice if there was an extension that added the timezone offset to a DateTime that resulted in a DateTimeOffset. 

Something like:

`1.November(2019).As(10, 0).WithOffset(-5)`

Thanks

**Comment by jnyrup** [comment]
You can also write it a bit more fluent with
`1.November(2019).At(10, 0).ToDateTimeOffset(-5.Hours())`

**Comment by gregveres** [comment]
@jnyrup I see where you are going with that, but it doesn't feel like it fits with the existing date fluent methods. 
I know it is a subjective opinion, but I feel like .WithOffset is more inline with the other methods like .November(<year>) and .As(<hour>, <minute>...)

**Comment by jnyrup** [comment]
I also like the naming `WithOffset` better than `ToDateTimeOffset`.
I would still make the signature `WithOffset(TimeSpan offset)` as not all time zones have integer offsets.

E.g. Nepal time is currently GMT+5:45.
Historically it gets even weirder, as e.g. Europe/London observed `GMT-00:01:15` (yes, minus one minute and 15 seconds) until [December 1st 1847](https://github.com/eggert/tz/blob/master/europe).

It *could* be handled by `WithOffset(int hours, int minutes = 0, int seconds = 0)`, but for negative offsets, such as the second example above, it would be `WithOffset(0, -1, -15)` which I'm not very keen on. Both because of the two negations, and it reminds me of the at times confusing `TimeSpan` constructors, where I have to check the parameter names to read the code.

With `WithOffset(TimeSpan offset)` it would be `WithOffset(-1.Minutes().And(15.Seconds()))`.

**Comment by dennisdoomen** [comment]
@gregveres just so you know, we would welcome a PR :-)
