### ISSUE TITLE
NUnit discovery fails if nunit.framework assembly is not loaded

### ISSUE THREAD

**Issue by lazyboy1** [fluentassertions/fluentassertions#1428]
### Description

I have a private framework library that extends NUnit. In my tests projects I am not using any classes from NUnit directly except `Assert`. I recently changed a tests project to use FluentAssertions, which stopped running tests after the change. I eventually figured out that nunit.framework is not loaded and therefore discovery fails.

### Complete minimal example reproducing the issue

Repro repo: https://github.com/lazyboy1/NUnitNotLoadedRepro

### Expected behavior:

Tests should run.

### Actual behavior:

Tests don't run :)

### Versions

* FluentAssertions 5.10.3
* .NET Core 3.1

### Additional Information

I am pretty sure this is the same problem as described in #373 and solution should be the same.

**Comment by dennisdoomen** [comment]
Thanks for reaching out to us. Unfortunately this has nothing to do with FA. Your `Tests.DoNotRun` project does not reference the `NUnit3` package, nor does it reference any code in that package. Because of that Visual Studio, R# or Rider will not detect any of the tests as NUnit tests. If you change the `Test1` test to be attributed by NUnit's `[Test]` attribute instead of your own, then you're project _does_ depend on NUnit and its assembly is loaded. Now the test runs as it should and FA throws the correct exception.

**Comment by lazyboy1** [comment]
I appreciate the quick response! I suppose I will stick with a workaround for now.
