### ISSUE TITLE
3.1.229 => references wrong libraries

### ISSUE THREAD

**Issue by dmytro-gokun** [fluentassertions/fluentassertions#146]
I've recently updated to the latest stable version from nuget (3.1.229).
My application uses .NET 4.5.
Now, it appears that FluentAssertions.3.1.229\lib\net45\FluentAssertions.Core.dll references System, System.Core and mscorlib of version 2.0.5.0
As a result, FluentAssertions.3.1.229\lib\net45\FluentAssertions.dll references two versions of mscorlib. And then my application also wants a refecence to System.Core 2.0.5.0...

At, at the end of the day all this drives ReSharper crazy :-(

**Comment by OregonGhost** [comment]
@dennisdoomen It's true that you can't change anything in FluentAssertions itself, but you can add that to the documentation. We ran into the problem when a product was updated from FA 2.x to 3.x. The tests ran fine anywhere - except for the Build Server and only in one single unit test that uses BeNotEmpty(). I guess the developer machines had the update implicitly, because I couldn't find the KB number in my installed updates.

So maybe just adding a note in the docs (maybe here in the Wiki?) that you need to install [KB2468871](http://www.microsoft.com/en-us/download/details.aspx?id=3556) may save a few people's days :)
