### ISSUE TITLE
CompleteWithinAsync does not consider execution time of sync code 

### ISSUE THREAD

**Issue by xzxzxc** [fluentassertions/fluentassertions#1761]
### Description

I have two equivalent tests of function that returns Task. First one uses `CompleteWithinAsync()` method, second one `ExecutionTime()`. Inside function before async part there is some sync code, but for simplicity of example I changed it to `Thread.Sleep()`.

```csharp
[Fact]
public async Task Test1()
{
    var func = async () => Thread.Sleep(10);
    await func.Should().CompleteWithinAsync(1.Milliseconds());
}

[Fact]
public void Test2()
{
    var func = async () => Thread.Sleep(10);
    func.ExecutionTime().Should().BeLessThan(1.Milliseconds());
}
```

### Expected behavior:

Two tests fail.

### Actual behavior:

First test does not fail.

### Versions
I'm using Fluent Assertions version 6.2.0 with net6.0 and c# 9.

**Comment by jnyrup** [comment]
I can confirm the issue.

The cause is that we invoke the `Func<Task>` before starting measuring time.
So any initial sync work is done before we call `Task.WhenAny`.
https://github.com/fluentassertions/fluentassertions/blob/f6c65c164ab0771b35c115b821bf3daac95bbea8/Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs#L50-L53

https://github.com/fluentassertions/fluentassertions/blob/f6c65c164ab0771b35c115b821bf3daac95bbea8/Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs#L41-L44
