### ISSUE TITLE
Removal of BinaryFormatter in .NET 8.0

### ISSUE THREAD

**Issue by MullerWasHere** [fluentassertions/fluentassertions#1779]
### Description

Due to [security issues](https://aka.ms/binaryformatter), `BinaryFormatter` [will be removed in .NET 8.0](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-8-nov-2023) and its `Serialize` and `Deserialize` methods are currently obsolete in .NET 5.0.

There is currently a single use of `BinaryFormatter`'s `Serialize` and `Deserialize` methods:
https://github.com/fluentassertions/fluentassertions/blob/834a2db00a60e2626655a28a129c084831b85880/Src/FluentAssertions/ObjectAssertionsExtensions.cs#L142-L153

Although it's a long way off until `BinaryFormatter` is removed, I figured it'd be a good idea to bring some attention to it. I stumbled upon this while working on #1754.

**Comment by lg2de** [comment]
When `BinaryFormatter` will be removed in net8, the assertion `BeBinarySerializable` should be removed, too. It gets useless.
So, I would recommend to exclude these methods (in `ObjectAssertionExtensions.cs`) using `#if NET8`.
This will solve the compilation of the FA library and its tests.

It will not solve the runtime of customers while there is no net8 target with the update above.
This means, FA 6.X will stop working when users are start using net8 (incl. preview), isn't it?
But, it applies only to users which are actively using `BeBinarySerializable`. If they hit the issue in FA they also hit the issue in its production code.

So I guess there is no additional action needed.
If you agree I can provide a PR with the `#if`s even there is no net8 target yet, but it should solve one blocker for the new target.

Should we add the `Obsolete` attribute to the assertion?
Because it is a breaking change it should get obsolete only with v7, I guess.

**Comment by dennisdoomen** [comment]
You would still need to have FA target .NET 8 to make that work. I recommend to wait a couple of days. As soon as #2152 has been merged, we're going to release 6.12 and switch `develop` to become the next major release.

**Comment by jnyrup** [comment]
The `BinaryFormatter` _type_ is still available with .NET 8, otherwise it would no longer implement .netstandard2.0 and cause  `MethodNotFoundException`s.

When ignoring the various SYSLIB errors about `BinaryFormatter` I can:
Target our tests against .NET 8, consuming the current .NET 6 FA dll and tests on `BeBinarySerializable` fails on runtime with.

```
BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."
```

I can also target and compile FA against .NET 8.
Running .NET 8 tests consuming the .NET 8 FA gives the same outcome as above.

This is not draw any final conclusions, just to clear up what can/cannot compile and what fails at runtime.

**Comment by dennisdoomen** [comment]
> This is not draw any final conclusions, just to clear up what can/cannot compile and what fails at runtime.

I'm not sure what you mean with that, but if I understand it correctly, we have two options:

1. Add a target for .NET 8 and make sure the corresponding API is not available, but keep it available for other targets
2. Rip it out completely

**Comment by jnyrup** [comment]
Correct

**Comment by dennisdoomen** [comment]
I vote for 2. Microsoft has clearly marked it as deprecated.

**Comment by lg2de** [comment]
I prepared the following:
1. Remove in net8
2. Obsolete otherwise 

This helps the users to migrate. Why we should remove it from targets, where it is still supported?

**Comment by jnyrup** [comment]
If we add .net8 only to exclude that API, we get a fragmented API, which can confuse users.
#1557 is an example where such a fragmentation causing confusion.

Technically there's also a third option: do nothing.

Pros:
* `BeBinarySerializable` is still available to targets that support it.
* We don't have to add an extra TFM only to remove an API.

Cons:
* Using `BeBinarySerializable` on .NET8 will throw an exception at runtime.

**Comment by lg2de** [comment]
Sure, "do nothing" is an option. But, the feature is obsolete for quite long time.
I'v marked it "obsolete", so we can follow Microsoft's plan and remove it completely in V8 of FA.

There is no need to add net8 target NOW.
My PR is just net8 ready.

**Comment by jnyrup** [comment]
If we want to eventually remove `BeBinarySerializable` completely from FA for all TFMs, we could also just remove it now and put the burden on consumers of figuring out a migration before they upgrade from v6 to v7.

As I recall in FA we have used `[Obsolete]` between major releases to indicate removal in the next-coming major release.

**Comment by dennisdoomen** [comment]
Let's remove it altogether then. If enough people start to complain, we can always add that extra target.

**Comment by jnyrup** [comment]
> If enough people start to complain, we can always add that extra target.

Or people can copy the code, or we can publish `FluentAssertions.BinaryFormatter` to keep the core library minimal.

**Comment by eNeRGy164** [comment]
I also wanted to suggest making it a separate library that just doesn't target 8.0. It will also be small and not really change as it will be feature complete immediately.
