### ISSUE TITLE
Consider ShouldThrow<TException>(this Task task)

### ISSUE THREAD

**Issue by lessneek** [fluentassertions/fluentassertions#190]
``` csharp
public static void ShouldThrow<TException>(this Task task) where TException : Exception
{
    Func<Task> func = () => task;
    func.ShouldThrow<TException>();
}
```

**Comment by vossad01** [comment]
I am guessing your second line is meant to be `Func<Task> func = () => task.Result;`?

It does seem we don't have much sugar for Tasks in FA.

I suppose this is really a question of whether whether the methods `Should(Not)Throw(Exactly)`.  I can see how that could be useful.  I have always just done an `await` myself, and probably would continue to do so because conceptually I do not think of Tasks as throwing exceptions.

[`Awaiting`](https://github.com/dennisdoomen/fluentassertions/pull/143) was recently added which may be in a in a similar vein to this though is certainly not the same.

**Comment by dennisdoomen** [comment]
We do have something similar for `Func<Task>`
