### ISSUE TITLE
BeEquivalentTo throws a NullReferenceException

### ISSUE THREAD

**Issue by DenisSokol** [fluentassertions/fluentassertions#1932]
### Description
while running tests in parallel ( 2 threads) and when using `BeEquivalentTo()` to compare objects from two lists a null reference exception is thrown.
However no NRE is thrown on using single thread
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.ToString()
```
```cs
public class Option
{
    public string Id { get; set; }
    public string Name { get; set; }
}
List<Option> expectedOptions;
List<Option> actualOptions;
```
### Complete minimal example reproducing the issue
```cs
// Arrange
List<Option> expectedOptions = new List<Option>
{
    new Option()
    {
        Id = "4b71bcd9",
        Name = "AutoTest_123"
    }
};

// Act
List<Option> actualOptions = new List<Option>
{
    new Option()
    {
        Id = "4b71bcd9",
        Name = "AutoTest_123"
    }
};

// Assert
for (var i = 0; i < expectedOptions.Count; i++)
{
    expectedOptions [i].Should().BeEquivalentTo(actualOptions[i]);
}
```
### Expected behavior:
The assertion should be true.

### Actual behavior:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.ToString()
```

### Versions
FluentAssertions Version="6.7.0"

**Comment by jnyrup** [comment]
Please include a _complete_ and _minimal_ example that we can run, i.e. a snippet I can copy directly into an IDE an run.
I can't see what an `Option` is.

**Comment by DenisSokol** [comment]
> Please include a _complete_ and _minimal_ example that we can run, i.e. a snippet I can copy directly into an IDE an run. I can't see what an `Option` is.

Sure thing, I've updated my question

**Comment by lg2de** [comment]
This is still not valid code.
Fixing the bugs, the problem is not reproducible!

**Comment by jnyrup** [comment]
I tried this on my machine to reproduce the error, but no errors occurred.
```cs
Parallel.For(0, 10000, new ParallelOptions { MaxDegreeOfParallelism = -1 }, _ =>
{
    List<Option> expectedOptions = new List<Option>
    {
        new Option()
        {
            Id = "4b71bcd9",
            Name = "AutoTest_123"
        }
    };

    List<Option> actualOptions = new List<Option>
    {
        new Option()
        {
            Id = "4b71bcd9",
            Name = "AutoTest_123"
        }
    };

    for (var i = 0; i < expectedOptions.Count; i++)
    {
        expectedOptions[i].Should().BeEquivalentTo(actualOptions[i]);
    }
});
```

Have you tried reproducing the error in a fresh project?
Are you using `AssertionOptions.AssertEquivalencyUsing`?
I recall someone have had concurrency problems because they used that method in a non-intended way.


The error indicates the problem lies somewhere, but nothing strikes me  https://github.com/fluentassertions/fluentassertions/blob/d77966dcd1770d77c274ef29086c407df0985999/Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs#L730-L814

**Comment by DenisSokol** [comment]
Nope, no using AssertionOptions.AssertEquivalencyUsing on my end. I'll stick with NUnit assertions as it works with no issues running tests in parallel though

**Comment by dennisdoomen** [comment]
We run thousands of tests in parallel using xUnit and FluentAssertions for the last 10 years. We never experienced anything like that. _If_ there was a concurrency issue, the problem was always with the code under test. 

So to diagnose this, we need more information. It's also weird that I don't see line numbers in your stack trace.

**Comment by jnyrup** [comment]
We have had a few bug fixes related the concurrency issues in the library itself 😉 
Events: #325, #1773
Caching: #864, #1091

Here are two cases where the problem was calling methods that are by-design not thread-safe.
Configuration: #714, #1323

I'd _love_ if you have time to help us dig into what is causing this issue for you.
If not a bug in the library then an explanation of why it happens could help others hitting the same problem.

Is the problem reproducible for you or did it only happened once?
Do you use anything from the classes `AssertionOptions`, `EquivalencyPlan` in any tests?
Which framework does the unit test project targets?
What operation system are you running the tests on?

**Comment by DenisSokol** [comment]
@jnyrup I've updated the previous post and uploaded test framework skeleton

**Comment by jnyrup** [comment]
Thanks for the complete example, it made it a _lot_ to diagnose.

`ApiTestHelper.GlobalSetUp` is invoked concurrently for both tests and _does_ call `AssertionOptions.AssertEquivalencyUsing` which is not safe.

One way to solve it is to move the setup of Fluent Assertions into a [`Module Initializer`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers) which are guaranteed to only run once.

```cs
[System.Runtime.CompilerServices.ModuleInitializer]
internal static void SetupFluentAssertions()
{
    AssertionOptions.AssertEquivalencyUsing(options => options
        .Using<DateTimeOffset>(ctx => ctx.Subject.Should().BeSameDateAs(ctx.Expectation))
        .WhenTypeIs<DateTimeOffset>()
        .Using<DateTime>(ctx => ctx.Subject.Should().BeSameDateAs(ctx.Expectation))
        .WhenTypeIs<DateTime>()
    );
}
```

**Comment by DenisSokol** [comment]
@jnyrup, Thanks a lot for digging into the problem resolving. I appreciate your help. It works now!

**Comment by dennisdoomen** [comment]
Maybe we could add some detection logic that throws when you try to call the `AssertionOptions` concurrently....

**Comment by jnyrup** [comment]
We _could_ add a lock inside `AssertEquivalencyUsing` to avoid concurrent calls modifying thread-unsafe collections and getting lists with null values, which I believe was one of kind of exception I saw.
It won't guard against getting a "Collection was modified; enumeration operation may not execute" exception though.

I don't think we should serialize reading `AssertionOptions.defaults`.

It valid to call `AssertEquivalencyUsing` multiple times, but requires carefulness, so we shouldn't limit invocations to a single one.

My concern about this is how much it helps, as it might just hide that it's still unsafe to call multiple times as it can change the outcome of a test.

**Comment by JakobFerdinand** [comment]
I just got the same error and it nearly drove me crazy because it occurred only randomly.
The solution with `[System.Runtime.CompilerServices.ModuleInitializer]` seams to solve the problem for me.
I think a generell threadsafe behavior would be be great!

**Comment by dennisdoomen** [comment]
> It valid to call AssertEquivalencyUsing multiple times, but requires carefulness, so we shouldn't limit invocations to a single one.

I only meant trying to detect _concurrent_ calls. That should never happen. Successive calls are fine.
