### ISSUE TITLE
BeEquivalentTo on strings does a case-insensitive comparison 

### ISSUE THREAD

**Issue by ParanoikCZE** [fluentassertions/fluentassertions#1947]
### Description

I'm trying to find a simple global way to handle a null string as empty, but it looks like equivalency is not called correctly on the string itself but only if encapsulated.

### Complete minimal example reproducing the issue

```csharp
public class Model
{
    public string val = null;
}

[Test]
public void Test()
{
    AssertionOptions.AssertEquivalencyUsing(options => options
        .Using<string>(ctx => (ctx.Subject ?? string.Empty).Should().BeEquivalentTo(ctx.Expectation ?? string.Empty))
        .WhenTypeIs<string>());

    using (new AssertionScope())
    {
        //this pass
        new Model() { val = "" }.Should().BeEquivalentTo(new Model());

        //this fails
        "".Should().BeEquivalentTo(null);
    }
}
```

### Expected behavior:

Equivalency is called properly with applied options.

### Actual behavior:

Equivalency options are not applied, probably because equivalency is not properly called.

### Versions

FluentAssertions 6.7.0
.NET 6.0

**Comment by dennisdoomen** [comment]
That's by design unfortunately. Because of historical reasons, `BeEquivalentTo` on `string` does a case-insensitive comparison. It has nothing to do with the deep comparison `BeEquivalentTo` does. We've considered to fix that, but even if we would introduce a separate method for doing the case-insensitive comparison, it would result in weird behavior. 

However, I think it's something we should be considering.

**Comment by dennisdoomen** [comment]
Duplicate issue as described in #2064
