### ISSUE TITLE
Missing ThrowWithinAsync similar to CompleteWithinAsync

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#2034]
We have already the assertion `CompleteWithinAsync` for asynchonous operations. This is a check with timeout in addition to `NotThrowAsync`.
Further we can assert `ThrowAsync` when expecting exceptions. Now I'm often missing `ThrowWithinAsync` when expecting exception and required timeout check.

In #1974 I already added proove-of-concept.
What do you think?

**Comment by jnyrup** [comment]
For completeness here's what we currently offer for `AsyncFunctionAssertions`.

```cs
Task<AndConstraint<TAssertions>> CompleteWithinAsync(TimeSpan timeSpan) {}
Task<AndConstraint<TAssertions>> NotCompleteWithinAsync(TimeSpan timeSpan) {}
Task<AndConstraint<TAssertions>> NotThrowAfterAsync(TimeSpan waitTime, TimeSpan pollInterval) {}
Task<AndConstraint<TAssertions>> NotThrowAsync() {}
Task<AndConstraint<TAssertions>> NotThrowAsync<TException>() {}
Task<ExceptionAssertions<TException>> ThrowAsync<TException>() {}
Task<ExceptionAssertions<TException>> ThrowExactlyAsync<TException>() {}
```

I think adding this seems reasonable :+1: 
```cs
Task<ExceptionAssertions<TException>> ThrowWithinAsync<TException>(TimeSpan timeSpan) {}
```

**Comment by lg2de** [comment]
Fine, then please check whether and how I should complete #1974.

**Comment by jnyrup** [comment]
I'll wait for @dennisdoomen to approve.

**Comment by dennisdoomen** [comment]
Sure, totally fine with it.

**Comment by julealgon** [comment]
Question/food for thought: would it be possible to model this "window of time" in a more orthogonal manner? One that didn't force particular overloads for all the scenarios?

So, instead of `ThrowWithin` we had a variation like `Throw().Within(timespan)`? (or `.Within(timespan).Throw()`, or any other variation).

This "dimension" then could have different methods, such as 
- Within
- After
- ...

PS: I'm coming here from the latest release notes... I had no idea this was open for such a long time.

Also, I assume this issue should've been closed already?

**Comment by jnyrup** [comment]
> Question/food for thought: would it be possible to model this "window of time" in a more orthogonal manner?

Possibly, can I ask you to open a discussion about this instead?
