### ISSUE TITLE
Cannot extract identifier from pathmapped file

### ISSUE THREAD

**Issue by commonquail** [fluentassertions/fluentassertions#2065]
### Description

I have

```xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10</LangVersion>
    <!-- https://stackoverflow.com/a/66221592/482758 -->
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    <!--
    <PathMap>$(MSBuildThisFileDirectory)=./</PathMap>
    -->
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.2.0" />
</ItemGroup>
```

I've observed this issue in the latest version, too.

That `PathMap` option translates a file name value like `C:\prefix\solution\project\file.cs` into `.\file.cs`.

With that `PathMap` option FluentAssertions is unable to locate the file and therefore cannot extract the identifier for its message, instead ending up with just `value` (which seems like it should have been `object`...?):

```
Xunit.Sdk.XunitException
Expected value to be 0M, but found -226290.0M.
Expected value to be 0M, but found -226290.0M.
Expected value to be 0M, but found -226290.00M.
Expected value to be 0M, but found -226290.0M.
Expected value to be 0M, but found -226290.00M.
Expected value to be 0M, but found -26067975.20M.
Expected value to be 0M, but found -26067975.2M.
Expected value to be 0.10440358M, but found 0.10287845M.
Expected value to be 0.10440358M, but found 0.10287845M.
Expected value to be 1M, but found 0M.
Expected value to be 1M, but found 0M.
Expected value to be 0M, but found -0.00865095M.
```

The failure happens inside [`CallerIdentifier::GetSourceCodeStatementFrom`](https://github.com/fluentassertions/fluentassertions/blob/59e96d419130dcf5b32ab968be53faa0b9df0963/Src/FluentAssertions/CallerIdentifier.cs#L195-L215). The redacted stack trace of the ignored exception is

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\<prefix>\<sln dir>\<project dir>\bin\Debug\net6.0\<fileName>'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at FluentAssertions.CallerIdentifier.GetSourceCodeStatementFrom(StackFrame frame)
```

Besides being bothersome in isolation this limitation has the knock-on effect of making `AssertionScope` basically useless with the `PathMap` option.

This clearly happens because the executable accesses the file relatively from its directory, not from the user's working directory. Is there ...

* a comparable configuration of `PathMap` that works?
* another way for FluentAssertions to retrieve the absolute missing prefix?
* a way to make FluentAssertions use the user (solution?) working directory?
* a way for FluentAssertions to determine the identifier that does not rely stack trace parsing, for example one of the Roslyn-populated compiler attributes?

FluentAssertions is pretty great. PathMap is also pretty great. I would like for them to become friends.

### Versions

* 6.2.0+
* .NET 6

**Comment by jnyrup** [comment]
> Besides being bothersome in isolation this limitation has the knock-on effect of making `AssertionScope` basically useless with the `PathMap` option.

Not sure I understand what part of `AssertionScope` is made useless?

> a way for FluentAssertions to determine the identifier that does not rely stack trace parsing, for example one of the Roslyn-populated compiler attributes?

I've added a note in #1677 to investigate if we can use `[CallerArgumentExpression]` to get the variable name.
I would _absolute_ love if that is possible to avoid trying to open files and "parsing" stack traces. 
It always reminds me of https://stackoverflow.com/a/1732454/1087627

> FluentAssertions is pretty great. PathMap is also pretty great. I would like for them to become friends.

If you'd like this to happen sooner we do accept pull requests :wink: 
If you're not up for that, you could experiment/reserarch if there anyway to know at runtime if a file is path mapped.

**Comment by commonquail** [comment]
> Not sure I understand what part of `AssertionScope` is made useless?

When an assertion fails inside an `AssertionScope` the stack trace points to the end of the scope, not the failing assertion (this makes sense). The example I demonstrated is the outcome of around 20 assertions on decimal properties, half of which failed. There is no way to tie the aggregate failure message or the stack trace to the assertions, therefore no way to see which assertions actually failed. As is, if I'm forced to choose between one of these configurations I'm going to have to choose not to use `AssertionScope` simply because it ceases to be effective.

> [...] `[CallerArgumentExpression]` [...]

This was also the option I'd reach for with my current understanding. Last time I used it on an extension method I believe I could only get the immediate identifier, i.e. not the prefix of an invocation chain. It would still be infinitely better than "value", though. I think this might even be possible to add to the `Should()` API already, though perhaps not possible to weave through.

There are some heuristics that can be used to increase the robustness of the file path accessing, like navigating up the tree a bit if the path is relative (the default output directory tends to be predictably structured). But all of those options overfit because the actual output directory can be arbitrarily specified, and anyway, the pathmapping can also hardcode a bogus absolute path.

Of course, one additional option is that I could conceivably disable `PathMap` for test projectsl. I actually have that ability right now and may pursue it. That's not a guaranteed option in general, though.

> if there anyway to know at runtime if a file is path mapped.

There are ways to generate files that contain values of MSBuild properties (because there is no other way to access their values, apparently), but as far as I can determine all useful properties get clobbered by the `PathMap` setting I demonstrated. Which is of course the point, really, but is an obstacle here.

**Comment by dennisdoomen** [comment]
`CallerArgumentExpression` is not an option until we drop .NET Core 2 support (which we can in v7). But given you're the first to _ever_ mention this, I wonder if it's worth solving in the first place. It's a test project, so why do you even want to fiddle with that flag? I'm in favor closing this issue.

**Comment by jnyrup** [comment]
Let's end the judging of .NET developers based on their knowings of FluentAssertions and `PathMap` ℹ️ 

> But given you're the first to ever mention this, I wonder if it's worth solving in the first place"

Just to expand here.
There's of course always a first reporter of any issue, but we always want to consider what complexity we add versus what cases it solves.
As you mention the obvious heuristics of guessing file paths might also be fragile, so I don't see we what to go down such a path.

> "The file is available at that location" is an assumption made by FluentAssertions that may have been valid once but is not any longer and has not been for a long time

We also assume that symbols are available, documented [here](https://github.com/fluentassertions/fluentassertions/blob/develop/docs/_pages/introduction.md#subject-identification), which is not necessarily true if compiling test projects in release mode.
Our recommendation here is also: if you want to benefit of the feature, build _test projects_ in debug mode.
The CI pipeline of FluentAssertions compiles the core lib in release mode and the test projects in debug mode exactly for this reason (and to test the core lib in the same configuration as we publish to nuget).

I would be absolutely fine also documenting that we currently do not support using `PathMap` for test projects.
Again, we welcome PRs

> The example I demonstrated is the outcome of around 20 assertions on decimal properties, half of which failed.

Without having seen your test code, it sounds like you could benefit from using `BeEquivalentTo`.
e.g. instead of
```cs
result.Foo.Should().Be(1);
result.Bar.Should().Be(2);
result.Baz.Should().Be(3);
```

compare `result` to an anonymous object. 
```cs
result.Should().BeEquivalentTo(new
{
    Foo = 1,
    Bar = 2,
    Baz = 3
});
```

>> I'm in favor closing this issue.
>
>  That's your prerogative. Please exercise it without disparaging my use case.

This was mostly a comment for me as we're discussing 99.9% of this library in the public.
Your goal to have completely reproducible builds is certainly desirable in these times of supply chain attacks, us closing an issue is simply a conclusion that this isn't going to change anything in Fluent Assertions.


To (try to) answer your initial set of questions:

* a comparable configuration of PathMap that works?
  * Not sure what is meant here.
* another way for FluentAssertions to retrieve the absolute missing prefix?
  * Not currently.
* a way to make FluentAssertions use the user (solution?) working directory?
  * Not currently.
* a way for FluentAssertions to determine the identifier that does not rely stack trace parsing, for example one of the Roslyn-populated compiler attributes?
  * Not currently, but we will look into using `[CallerArgumentExpression]` - #1677
