### ISSUE TITLE
DLR/dynamic support

### ISSUE THREAD

**Issue by artkpv** [fluentassertions/fluentassertions#234]
Hi, 
Is there a way to make FluentAssertions work with dynamic/DLR? Consider the following code:

```
            dynamic expando = new ExpandoObject();
        expando.someVar = "string";
        expando.someVar.Should().Be("string");
```

which throws `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException`: "'string' does not contain a definition for 'Should'"

Thanks!

**Comment by dennisdoomen** [comment]
Not until C# supports calling extension methods from dynamic objects...

**Comment by vossad01** [comment]
Usually dynamic users can still utilize Extension Methods by calling them as static methods.  Can anything reasonably be changed internally in FA to support this?

As is a `StackOverflowException` is thrown by the following example.  I only assume that it managed to get caught in some sort of infinite recursion between overloaded methods.

```c#
string d = "hi";
AssertionExtensions.Should(d).Be("yo");
```

Given a number of the recent .NET targets do not support `dynamic` I am not sure it is oft used enough that FA needs cater to it.  However, I believe it would at least be possible to at least prevent stack overflow by adding a `Should(dynamic)` method on platforms that support it.

Since NUnit's `Assert.That` constraint-based assertions do depend on the objects' types you might find those more suitable.  Alternatively, you could of course cast your dynamic object to be able to us FA's assertions.

**Comment by dennisdoomen** [comment]
@vossad01 But what should `Should(dynamic)` do?

**Comment by JowenMei** [comment]
Can't you use the equality operator, like in <code>Assert.AreEqual()</code>?
I'm also looking for a fluent alternative for: 
<code>Assert.AreEqual(controller.ViewBag.HelpUrl, "helpUrl value from settings"); </code>

**Comment by mpodonyi** [comment]
Is it not possible to use `.As<T>()` or `.BeOfType<>()` method to cast the dynamic value to a concrete one.
e.g:
```csharp
dynamic set = GetDynamic();
set.As<int>().Should().Be(6);
```
Looks better than:
```csharp
dynamic set = GetDynamic();
((int)set).Should().Be(6);
```

**Comment by w1ld** [comment]
@mpodonyi That [`.As<T>()`](https://github.com/dennisdoomen/fluentassertions/blob/57d3a4ea99ca39fe239006c7a5f93da71c7b9298/Src/Shared/AssertionExtensions.cs#L675) does not work. Throws `Microsoft.CSharp.RuntimeBinder.RuntimeBinderException`. As @dennisdoomen wrote DLR does not support extension methods so far. [Here](http://stackoverflow.com/questions/5311465/extension-method-and-dynamic-object) is interesting discussion. In short it can't search the method at runtime to match the object.

**Comment by TroySijuwade** [comment]
@artkpv , @JowenMei I note this is over 2 years late ;) ... and for the benefit of those still trying to figure out how to do this, I was able to do this using FluentAssertions:

((string) result.ViewBag.HelpUrl).ShouldBeEquivalentTo("helpUrl value from settings");

**Comment by dennisdoomen** [comment]
The situation will be a bit better with 5.0 because the object being compared with will be what is used to traverse the object graph instead of the SUT.

**Comment by WhatFreshHellIsThis** [comment]
Has anything now changed with 5.0?  (I need to test dynamic objects with a REST api)

**Comment by dennisdoomen** [comment]
Unless there's a way to define a `Should()` extension method that acts on dynamic, no

**Comment by lycandroid** [comment]
I am using cast to object as a workaround, but where I am specifically wanting to test the type of a dynamic e.g.
```cs
// field.value is dynamic
field.value = "xyz";
((object)field.value).Should().BeOfType(typeof(string));
```
FWIW the same cast would work for the OP
```cs
 ((object)expando.someVar).Should().Be("string");
```
