### ISSUE TITLE
Equivalency assertion option Excluding outputs "value(...<>c__DisplayClass).variableName" in some instances

### ISSUE THREAD

**Issue by PortalDweller** [fluentassertions/fluentassertions#2611]
### Description

When comparing two objects with `BeEquivalentTo`, using `options.Excluding(p => p.Path == someVariable)`, the configuration options list the exclusion rule as such:

`- Exclude member when (p.Path == value(FluentAssertions.ExcludingConfigOutput.ExcludingConfigOutputTest+<>c__DisplayClass3_0).someVariable)`

We are trying to set one or more exclusions passing a string variable for the `p.Path == someVar` equality check.

Of course when we change to `p.Path == "FirstName"` the exclusion rule is output as expected, but we are trying to configure the exclusion rules dynamically.

### Reproduction Steps

```csharp
Person subject = new Person() { FirstName = "David", LastName = "Smith", };
Person expected = new Person() { FirstName = "Otto", LastName = "Wilson", };

var variableName = "FirstName";

subject.Should().BeEquivalentTo(expected, options => 
   options.Excluding(p => p.Path == variableName));
```

### Expected behavior

```
Expected property subject.LastName to be "Wilson" with a length of 6, but "Smith" has a length of 5, differs near "Smi" (index 0).

With configuration:
- ...
- Exclude member when (p.Path == "FirstName")
- ...
```

### Actual behavior

```
Expected property subject.LastName to be "Wilson" with a length of 6, but "Smith" has a length of 5, differs near "Smi" (index 0).

With configuration:
- ...
- Exclude member when (p.Path == value(FluentAssertions.ExcludingConfigOutput.ExcludingConfigOutputTest+<>c__DisplayClass1_0).variableName)
- ...
```

### Regression?

Not that I know of

### Known Workarounds

None that I could find

### Configuration

Fluent Assertions 6.12.0
.NET 8.0

### Are you willing to help with a pull-request?

No

**Comment by jnyrup** [comment]
This is because the variable `variableName` is referenced rather than simply it's value from the `Expression<>` passed to `Excluding`

As a workaround you can make `variableName` `const`.

See this [example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AGQEs8BHZgUQQAOsAM7D2EPMIDc1akwYA3AIZR2S4ABsYAOSUBbGPQC89AEQAxdlGEZdB0zKr8wGnABNOAcwAUEYwD56CGYABSUMAAtjE2VVdS07GABKR2pISQxGMkUVNU0dfRgAYQkbYzNLa1tCh2pnVw88Hz8jQOCwyOj6WLyEwpKMlNkaFHp69y9vfiEYUXE8AB4iAFYFgEkAWRg9YBgoNbwAMwg0emAICA1/QJmPMHDk6gBvano3rIBOb1v2e4wYZgAIQgbgAnkMqABfYZEADM9E4/yghyUYEMm22u32Rwgz1e73k9A6USe9E8MAwUnowgpVOhUKAA)

**Comment by dennisdoomen** [comment]
And as we rely on .NET to provide us with a string representation of the expression, that's what you get. Unless we find a well-maintained library that we can safely use, there's not much we can do to solve this.
