### ISSUE TITLE
[Feature]: Consider updating the ConfigurationManager transitive dependency version

### ISSUE THREAD

**Issue by ViktorHofer** [fluentassertions/fluentassertions#2668]
### Background and motivation

When referencing the FluentAssertions nuget package a five years old version of the System.Configuration.ConfigurationManager package gets referenced transitively. Those ancient 4.x.x versions of "System" nuget packages will eventually get marked as deprecated. Consider upgrading the ConfigurationManager version to something in support, i.e. 6.0.1.

This only impacts the net6.0 as it's the only TFM that references the package.

### Are you willing help with a pull-request?

Yes, please assign this issue to me.

**Comment by dennisdoomen** [comment]
I think that should be okay, as long as we use the lowest version compatible with .NET 6.0. So indeed, 6.0.1. You agree @jnyrup ?

**Comment by jnyrup** [comment]
Let's bump it. 
Thanks for the heads up @ViktorHofer

**Comment by ITaluone** [comment]
What about bumping `System.Threading.Tasks.Extensions` to 4.5.4 in the same go?

Applies to netstandard2.0 and net47..

**Comment by ViktorHofer** [comment]
Submitted https://github.com/fluentassertions/fluentassertions/pull/2673

**Comment by jnyrup** [comment]
> What about bumping `System.Threading.Tasks.Extensions` to 4.5.4 in the same go?
> 
> Applies to netstandard2.0 and net47..

In general we want to use the lowest possible available libraries for the FA core library.

Imagine an application `app` having a dependency on `System.Threading.Tasks.Extensions@4.5.0`

Upgrading `System.Threading.Tasks.Extensions` in FA to 4.5.4 gives us this dependency graph.
```
tests -> app -> System.Threading.Tasks.Extensions@4.5.0
      -> FA -> System.Threading.Tasks.Extensions@4.5.4
```

Unit tests might now be testing a different behavior than what happens when `app` runs in production.
Especially tests-only libraries should be very aware of this.

That said, I'm fine with also bumping `System.Threading.Tasks.Extensions`

**Comment by ITaluone** [comment]
> Imagine an application app having a dependency on System.Threading.Tasks.Extensions@4.5.0

What about the other way round? It's the same thing, no?

```
tests -> app -> System.Threading.Tasks.Extensions@4.5.4
      -> FA -> System.Threading.Tasks.Extensions@4.5.0
```
