### ISSUE TITLE
support for NotContainInOrder

### ISSUE THREAD

**Issue by SurajGupta** [fluentassertions/fluentassertions#318]
I would be great to get an generic collection assertion `NotContainInOrder()`

**Comment by dennisdoomen** [comment]
Sure. Would you be willing to send me a PR?

**Comment by blairconrad** [comment]
I wasn't sure what `NotContainInOrder` meant, so I went searching the web to find out if it's a thing that I just hadn't heard of. I found

StackOverflow question [How to assert two lists are not equivalent if in different order using Fluent Assertions](http://stackoverflow.com/questions/29281224/how-to-assert-two-lists-are-not-equivalent-if-in-different-order-using-fluent-as), which used the term to mean a test that would pass if

1. two collections contained the same elements, but
2. the two collections' orders were not the same

so

|collection 1|collection 2|result|
|-------------|--------------|------|
|1, 2, 3|1, 4, 3, 2|fail|
|1, 2, 3|3, 1, 2| pass|
|1, 2, 3|1, 2, 3|fail|

Essentially, it would be the same as checking

if the lists are equivalent, without regard to order, and if the lists are NOT equivalent when considered with strict ordering.

Am I on the right track?

**Comment by dennisdoomen** [comment]
SurajGupta, can you confirm?

**Comment by blairconrad** [comment]
However @SurajGupta replies, I'd suggest a different name for the constraint. I'm a native speaker of English, and "not contain in order" does not mean anything to me. Every time I tried to use such a method, I'd have to refer to the documentation.

**Comment by dennisdoomen** [comment]
You can't say *this collection should not contain the other collection in order*?

**Comment by blairconrad** [comment]
Oh! I think you're understanding the intent better than I am. Let's augment my table from above, with my understanding.

|actual|expected|result|
|-------------|--------------|------|
|1, 2, 3|1, 4, 3, 2|fail|
|1, 2, 3|3, 1, 2| pass|
|1, 2, 3|1, 2, 3|fail|
|1, 2, 3, 4, 5|2, 3, 4| ??? |

I had thought that last entry would be a "pass" because I thought @SurajGupta wanted to reject only expected values that were exactly the same as actual, in order. But you are saying it should be "fail" because actual _contained expected's elements in order_.

If that's correct, then `NotContainInOrder` is not so bad. I still would not figure it out without docs, but it might stick in my head after I read them.

I'd consider `NotContainSequence`, as "sequence" suggest to me an ordered collection with no gaps. But I wouldn't fight very strongly for that as a new name.

**Comment by krajek** [comment]
I can tackle it, but we have to agree on the last test case that @blairconrad provided.
I think that the results should be 

actual | expected | result
-- | -- | --
1, 2, 3 | 1, 4, 3, 2 | fail
1, 2, 3 | 3, 1, 2 | pass
1, 2, 3 | 1, 2, 3 | fail
1, 2, 3, 4, 5 | 2, 3, 4 | **fail**
1, 2, 3, **5, 4** | 2, 3, 4 | **fail**

Last two fail, because they contain 2,3,4 in order. The last one contains 2,3,4 in order, even though 5 is between 3 and 4.
What do you think?

**Comment by dennisdoomen** [comment]
I find the table a bit difficult to reason about. What's _actual_, what's _expected_, and what does _pass_/_fail_ mean?

**Comment by blairconrad** [comment]
"expected" would be the collection passed as the first argument to `NotContainInOrder`. I used it in the same sense as it's used in [BeSameAs](https://github.com/fluentassertions/fluentassertions/blob/fe0af34e08f611d24c27414b67f6e694c3c1d651/Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs#L79). 

"actual" was not the best choice. Probably "subject" is closer to the usual FluentAssertions parlance.

And to me "fail" meant that the assertion would throw. "pass" meant it would not. In this case, that would mean returning an `AndConstraint`, I believe.

**Comment by krajek** [comment]
Good points regarding vocabulary. Let me just rewrite the table once again in FA terms. Note, that compared to the previous table I changed the first result.

`subject.Should().NotContainInOrder(expected);`

subject| expected | assertion throws
-- | -- | --
1, 2, 3 | 1, 4, 3, 2 | **no**
1, 2, 3 | 3, 1, 2 | no
1, 2, 3 | 1, 2, 3 | yes
1, 2, 3, 4, 5 | 2, 3, 4 | yes
1, 2, 3, 5, 4 | 2, 3, 4 | yes

**Comment by jnyrup** [comment]
I'm not very keen on the name due to two reasons:

---

Compare `ContainInOrder` to `NotContainInOrder`

1) `ContainInOrder` is a contraction of containing *and* being in order.
2) Prefixing an assertion with `Not` should give the negated assertion.

The formal logically negation of "containing and being in order" is:
"not containing or not being in order", or formulated in a sentence
"subject should not contain elements but if it does elements should not be in order".

What I hear being discussed here is:
* `elements` should be a subset of `subject`, and
* the elements of `elements` can be in any order inside `subject` but ordered.

I think `ContainButNotInOrder` would be a more descriptive name for that case.

---

What do we mean by `(IEnumerable subject).Should().Contain(IEnumerable expected)`? (ignore the invalid syntax)

As formulated [here](https://stackoverflow.com/a/10409944/1087627)
>`IEnumerable/IEnumerable<T>` makes no guarantees about ordering, but the implementations that use `IEnumerable/IEnumerable<T>` may or may not guarantee ordering.
> For instance, if you enumerate `List<T>`, order is guaranteed, but if you enumerate `HashSet<T>` no such guarantee is provided, yet both will be enumerated using the `IEnumerable<T>` interface.

And I would extend that to say that `ICollection<T>` also makes no guarantees about the ordering.
The mental picture is that a bag is a collection and there is no guarantee of the ordering inside a bag.

Currently the ambiguity is "resolved" in the documentation for `ContainInOrder`
> Expects the current collection to contain the specified elements in the exact same order, not necessarily consecutive.

According to that summary `expected` is in order by definition and not how `OrderBy` would sort them.
As a [subsequence](https://en.wikipedia.org/wiki/Subsequence) is not necessarily consecutive I think `ContainSubsequence` would be more clear.

**Comment by dennisdoomen** [comment]
You have a point here. Maybe `ContainOutOfOrder` is a better fit.

Changing the existing API is not in scope of 5.0 anymore. I want to finalize the remaining issues with a couple of RCs and then ship it.

**Comment by krajek** [comment]
@dennisdoomen yes, of course, everything discussed here is just clarification. Implementation to be done after the release.

---

Once again I will post a design table, but this time I include ContainInOrder.

A: `subject.Should().NotContainInOrder(expected);`
B: `subject.Should().ContainInOrder(expected);`

subject | expected | assertion A throws | assertion B throws
-- | -- | -- | --
1, 2, 3 | 1, 4, 3, 2 | no | yes
1, 2, 3 | 3, 1, 2 | no | yes
1, 2, 3 | 1, 2, 3 | yes | no
1, 2, 3, 4, 5 | 2, 3, 4 | yes | no
1, 2, 3, 5, 4 | 2, 3, 4 | yes | no

As you can see `NotContainInOrder` would be a logical negation of `ContainInOrder`. For that reason and for the consistency with the rest of the API (pairs like `EndWith`/`NotEndWith` or `IntersectWith`/`NotIntersectWith`) I would vote for keeping the initially proposed name `NotContainInOrder`.

`ContainOutOfOrder` and `ContainButNotInOrder` suggest different behaviour than the one presented in the table. They would throw in case of `subject` not containing `expected` (first row in the table), whereas `NotContainInOrder` would not throw.

**Comment by rynkevich** [comment]
Since this issue is stuck for more than two years already, I've decided to push it forward.

I'm not a native speaker of English, but I think that `NotContainInOrder` is the best option from the formal logic perspective. The latest version of a design table, posted by @krajek, is absolutely correct and clear, the name and the logic of the assertion would also be consistent with existing API.

I have created a [PR](https://github.com/fluentassertions/fluentassertions/pull/1339) with my vision of this assertion.

**Comment by krajek** [comment]
@rynkevich thanks for the PR.
Out of curiosity: what is your real-life use case for this assertion?

**Comment by rynkevich** [comment]
@krajek, I don't have such, just looking around for some work :grinning:, though I hope it will be useful to someone, maybe @SurajGupta who has originally asked for this feature

**Comment by SurajGupta** [comment]
Thanks for this!  I actually wrote my own assertion library because I was frustrated with FluentAssertions and others.  But it has no documentation so no one is going to use it until I can get that done. =)    https://github.com/OBeautifulCode/OBeautifulCode.Assertion

**Comment by dennisdoomen** [comment]
> actually wrote my own assertion library because I was frustrated with FluentAssertions and others

What made you so frustrated?

**Comment by SurajGupta** [comment]
I'm planning to write a blog post about my framework at some point, so the following thoughts are not complete nor organized, but after that dropping that comment I do owe you some more details...

My frustrations started here: https://github.com/fluentassertions/fluentassertions/issues/357

Then it hit me that assertions as extensions methods on specific types, as an overarching framework concept, was too limiting versus an approach where you determine, in runtime, whether an assertion can be applied to a type.  While the former approach gets you compile safety and bettter performance, you sacrifice grammar, which was a deal-breaker for me.  For example, how to solve for the bug above?  At some point you run out of C# trickery and you need to add another assertion like ContainsKeyInReadOnlyDictionary to work-around the shared interface issue.

Then that got me thinking - I was lukewarm on the assertion names in FA and it was appealing to name assertions as I wanted to write them (e.g. BeEqualTo instead of Be, BeSameRefererenceAs instead of BeSame).  I also found myself having to refer back to the documentation a lot in the whole equals/equavalent/contains space in asserting against enumerables/lists/collections/dictionaries/etc.  Actually, that took me on an unexpected detour to make it super easy to determine if two objects are equal, respecting the "contract" of the declared type (e.g. two ILists are equal if they are SequenceEqual, whereas two ICollections are more like set/unordered equality).  I also really wanted to crack the nut on Dictionary equality and support types that were nested multiple levels (e.g. IReadOnlyDictionary<string, IList<...>>.  This is not really a FA issue; .NET doesn't help us here.  But "equal" assertions are common and so the pain-points are felt when using FA (i.e. having to perform multiple lines of assertions to get at a single concept - are these two things equal using reasonable conventions?).  Anyways, see https://github.com/OBeautifulCode/OBeautifulCode.Equality which also has no documentation, but has been a total pleasure to use in production code and backs any kind of equality/contains assertion in my library.

So then I got to thinking further - why do we use different frameworks for assertions in tests versus non-test methods?  If x == null then throw ArgumentNullException is an assertion.  There are frameworks out there for argument checking.  What about "mid-method" (so after you have validated your arguments) assertions that might throw something like InvalidOperationException (e.g. if someValueReturnedFromDatabase == bad then throw InvalidOperationException).  That's just an assertion.  Isn't it so much better to have a single consistent framework/grammar for assertions across your code base?  One issue is that you'd have a dependency on the assertion library EVERYWHERE.  Any consumer of a library that made these assertions would have to take the dependency and thus the consumer's consumers would have to take the dependency, and so on.  My assertion library install itself as code (my colleagues and I call these "recipes").  So it's compiled into the project and doesn't appear to the external world as a required package install.

So now I live in the world where my argument checking looks like this:
`new { someArgument }.AsArg().Must().NotBeNullNorEmptyEnumerable();`  (using an anonymous object you get the name of the argument for free in the resulting exception message, if an exception is thrown), but if you like you can also write `someArgument.AsArg(nameof(someArgument)).Must().NotBeNullNorEmptyEnumerable();`

otherwise, for InvalidOperationException, you might write this:
`valueFromDatabase.AsOp().Must().BeAlphanumeric(because: "usernames are limited to alpha-numeric characters")

and for tests:
`actual.AsTest().Must().BeEqualTo(expected);`

these are just some examples, there's more features.

Anyways, there's a lot here and I really need to get this organized and presented in a more compelling way, because now that I live in this world I would never go back.  The devs on my team feel the same way too =)

**Comment by dennisdoomen** [comment]
Thank you for taking the time to share your thoughts here. I see what you were trying to accomplish. And there's plenty of room in our eco system for another assertion framework.

**Comment by krajek** [comment]
@SurajGupta thanks as well. Happy to see you attack the problem from a completely different angle!

**Comment by dagilleland** [comment]
@krajek - Here's a situation for needing a **`ContainButNotInOrder`** (which I do think is a better name). It's for a deck of cards, to make sure it is randomized when reshuffled.

```csharp
    public class A_Deck_Of_Cards_Must
    {
        DeckOfCards deck = DeckOfCards.OpenNewDeck();
        // ... other tests
        [Fact]
        public void Be_In_A_Different_Order_When_Reshuffled()
        {
            deck.Shuffle();
            var firstShuffle = new List<PlayingCard>( deck.Cards);
            deck.Shuffle();
            var reshuffled = deck.Cards;
            reshuffled.Should().Contain(firstShuffle).And.;
        }
    }
```

Granted, it's not a "money-maker" example, but it's one I'm facing right now in creating samples for teaching OOP with Unit Tests.
