### ISSUE TITLE
IReadOnlyDictionary

### ISSUE THREAD

**Issue by laymain** [fluentassertions/fluentassertions#357]
Hi,

We should be able to call the ContainKey() extension on a IReadOnlyDictionary:

``` C#
IReadOnlyDictionary<TKey, TValue> dictionary;
dictionary.Should().ContainKey(...)
```

**Comment by abatishchev** [comment]
Please send a pull request. You can start form cloning [GenericDictionaryAssertions](https://github.com/dennisdoomen/fluentassertions/blob/master/Src/Core/Collections/GenericDictionaryAssertions.cs)

**Comment by laymain** [comment]
Indeed, I could. Hope I'll have time someday.

**Comment by dennisdoomen** [comment]
:+1:

**Comment by abatishchev** [comment]
@laymain this might sounds harder than it actually is. That's what I did (https://github.com/dennisdoomen/FluentAssertions/pull/186) and Denis accepted, merged and then released. Go for it!

Disclaimer: I'm not related to this project anyhow other than just being yet another random person from internets who uses it.

**Comment by laymain** [comment]
The problem is that everything seems to be based on IDictionary but unfortunately
IDictionary does not implement IReadOnlyDictionary as it should.

I'll have a look on what you have done, thanks.

**Comment by dennisdoomen** [comment]
You *could* change the current `GenericDictionaryAssertions` so that it takes an `IEnumerable<KeyValuePair<TKey, TValue>> and have two versions of the `Should` extension methods that use that internally, one acting on an `IDictionary<,>` and one acting on `IReadOnlyDictionary`. Alternatively, you could even have a single extension method that just takes the enumerable of key-value pairs.

**Comment by somewhatabstract** [comment]
I was looking into this and noticed a few things that may inform what direction to take.

First, I added a new assertion set for `IReadOnlyDictionary`, we can base it off the existing `IDictionary` variant and do some `ToDictionary` shenanigans in the construtor to leverage all the existing asserts. This works great, but it introduces an ambiguity that will break existing uses of the original assertions on `Dictionary` since it implements both the read-only and regular interfaces.

We could avoid that breaking change by adding a `Should()` specifically for `Dictionary` but it would still be breaking for anyone with their own types that do the same thing.

Second, we could change to base of `IEnumerable<KeyValuePair<TKey,TValue>>` as @dennisdoomen proposed. This is less error prone and should work (though I haven't tried it yet). The advantage would be that we could reuse the existing `IEnumerable` assertions for `HaveCount`, etc., however, the downside is that we'd probably have to do some magic for the `ContainKeys` and other such assertions (like trying to cast to dictionaries first, then doing it by hand if it isn't one).

Clearly, there are multiple directions to take here, but I felt it worth discussing first after my initial investigations. Thoughts? Suggestions?

**Comment by Mpdreamz** [comment]
@dennisdoomen we have the following in our code base: https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Tests.Core/Extensions/ReadOnlyDictionaryAssertions.cs

Which seems to have worked for us for a while, any interest in a PR? It won't address all the points raised by @somewhatabstract 

cc @russcam

**Comment by jnyrup** [comment]
@Mpdreamz Having a quick look at the code, it would be API breaking, as it introduces ambiguity for custom dictionaries implementing both `IDictionary<>` and `IReadOnlyDictionary<>`.
Similar to how you explicitly resolved it for the class `Dictionary<>`.

See this test 
https://github.com/fluentassertions/fluentassertions/pull/984/files

There is a Work-in-progress PR, which *might* come in a future major release.
https://github.com/fluentassertions/fluentassertions/pull/963

**Comment by flin-8** [comment]
Hi @jnyrup , any idea when this will be released?

Thanks!

**Comment by jnyrup** [comment]
@flin-8 Unfortunately not.
In the mean time, you might be able to do a workaround, depending on what types of dictionaries you assert on.

```cs
namespace FluentAssertions
{
    public static class Extensions
    {
        public static GenericDictionaryAssertions<TKey, TValue> Should<TKey, TValue>(this Dictionary<TKey, TValue> dict) =>
            new GenericDictionaryAssertions<TKey, TValue>(dict);

        public static GenericDictionaryAssertions<TKey, TValue> Should<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dict) =>
            dict is IDictionary<TKey, TValue> regularDictionary
                ? new GenericDictionaryAssertions<TKey, TValue>(regularDictionary)
                : throw new ArgumentException("Wait for FA 6.0");
    }
}
```

```cs
[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void Test_Dictionary()
    {
        Dictionary<int, string> dict = new Dictionary<int, string>
        {
            [42] = "foo"
        };

        dict.Should().ContainKey(42); // uses 1st custom overload
    }

    [TestMethod]
    public void Test_IReadOnlyDictionary()
    {
        IReadOnlyDictionary<int, string> dict = new Dictionary<int, string>
        {
            [42] = "foo"
        };

        dict.Should().ContainKey(42); // uses 2nd custom overload
    }

    [TestMethod]
    public void Test_IDictionary()
    {
        IDictionary<int, string> dict = new Dictionary<int, string>
        {
            [42] = "foo"
        };

        dict.Should().ContainKey(42); // uses builtin IDictionary overload
    }

    [TestMethod]
    public void Test_Only_IReadOnlyDictionary()
    {
        IReadOnlyDictionary<int, string> dict = new ReadOnlyDictionary<int, string>(
            new Dictionary<int, string>
            {
                [42] = "foo"
            });

        dict.Should().ContainKey(42); // uses 2nd custom overload but fails.
    }

    private class ReadOnlyDictionary<TKey, TValue> : IReadOnlyDictionary<TKey, TValue>
    {
        private readonly IReadOnlyDictionary<TKey, TValue> inner;

        public ReadOnlyDictionary(IReadOnlyDictionary<TKey, TValue> inner)
        {
            this.inner = inner;
        }

        public TValue this[TKey key] => inner[key];

        public IEnumerable<TKey> Keys => inner.Keys;

        public IEnumerable<TValue> Values => inner.Values;

        public int Count => inner.Count;

        public bool ContainsKey(TKey key) => inner.ContainsKey(key);

        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator() =>
            inner.GetEnumerator();

        public bool TryGetValue(TKey key, [MaybeNullWhen(false)] out TValue value) =>
            inner.TryGetValue(key, out value);

        IEnumerator IEnumerable.GetEnumerator() => inner.GetEnumerator();
    }
}
```
