### ISSUE TITLE
Extend ShouldThrow<TException> to cater for constructors

### ISSUE THREAD

**Issue by HisRoyalRedness** [fluentassertions/fluentassertions#376]
It would be nice to be able to test that constructors emit exceptions when given bad parameters. This is easy to do by creating a simple action that performs the construction, e.g.

```
Action testMe = () => new BigObject(-1);
testMe.ShouldThrow<ArgumentOutOfRangeException>("-1 is not a valid parameter");
testMe = () => new BigObject(42);
testMe.ShouldThrow<InvalidOperationException>("42 is not the answer");
```

It would be much easier on the eye to do this, and allows a whole range of testing with a single action.

```
Action<int> construct = i => new BigObject(i);
construct.ShouldThrow<ArgumentOutOfRangeException, int>(-1, "-1 is not a valid parameter");
construct.ShouldThrow<InvalidOperationException, int>(42, "42 is not a valid parameter");
```

**Comment by dennisdoomen** [comment]
I accept PRs you know :smile:

**Comment by HisRoyalRedness** [comment]
Slap on the wrist accepted...

I've checked my changes into a fork and just trying to get the Pull Request
sorted. Git is still a bit new for me...

**Comment by krajek** [comment]
@dennisdoomen my suggestion is to close this Issue as "won't fix".
Proposed syntax:

- isn't more readable, even less for my taste
- would be PITA to implement because we would need an overload for each arity of `Action (<T>, <T1, T2> etc.)`
- the goal of the feature could be easily implemented like this:

```
Action CreateWithParam(int x) { return new BigObject(x); }
CreateWithParam(-1).ShouldThrow<ArgumentOutOfRangeException, int>("-1 is not a valid parameter");
CreateWithParam(42).ShouldThrow<InvalidOperationException, int>("42 is not a valid parameter");
```

@HisRoyalRedness just asking: would you be cool with closing?

**Comment by HisRoyalRedness** [comment]
Yup, cool to close it

**Comment by dennisdoomen** [comment]
Agreed

**Comment by jez9999** [comment]
> * the goal of the feature could be easily implemented like this:
> 
> ```
> Action CreateWithParam(int x) { return new BigObject(x); }
> CreateWithParam(-1).ShouldThrow<ArgumentOutOfRangeException, int>("-1 is not a valid parameter");
> CreateWithParam(42).ShouldThrow<InvalidOperationException, int>("42 is not a valid parameter");
> ```

This doesn't seem to work, what am I missing here?  `CreateWithParam` is declared as a method that returns `Action`, but you're returning `BigObject`.

**Comment by jez9999** [comment]
A reason I would like to see some kind of syntax specifically catering to testing constructors is because the following triggers [rule CA1806](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1806):

```
Action newObj = () => new MyObject(1, 2, 3);
```

Yeah the rule could be ignored or suppressed but it'd be nice to have a form of code that doesn't trigger it.
