### ISSUE TITLE
ShouldRaisePropertyChangedFor followed by Count behaves unexpectedly (solution here)

### ISSUE THREAD

**Issue by Ryan-Palmer** [fluentassertions/fluentassertions#393]
I wanted to check the number of times `RaisePropertyChanged` had been raised for a particular property.

I expected to type:

```c#
myVm.ShouldRaisePropertyChangedFor(vm => vm.myProperty).Count().ShouldBeEquivalentTo(2);
```

This failed - the count returned was for ALL RaisePropertyChange events, not the specific one I am testing.

I have written a quick extension method:

```c#
public static int SpecificRaisePropertyChangedCount(this IEnumerable<RecordedEvent> value, string propertyName)
{
    return value.Select(r => r.Parameters)
        .SelectMany(s => s)
        .Count(p => p is PropertyChangedEventArgs && (p as PropertyChangedEventArgs).PropertyName == propertyName);
}
```

so you can now do:

```c#
myVm.ShouldRaisePropertyChangedFor(vm => vm.myProperty)
    .SpecificRaisePropertyChangedCount(nameof(myVm.myProperty))
    .ShouldBeEquivalentTo(2);
```

Sorry I haven't submitted this as a pull request - I'm up to my neck in it and no time to clone the repo etc, but feel free to add it or whatever (or tell me that I could have done it with the existing code easily ^_^ )

**Comment by dennisdoomen** [comment]
Thanks for reporting this. I'll take a look at it.

**Comment by BrunoJuchli** [comment]
This is caused by https://github.com/fluentassertions/fluentassertions/issues/337

**Comment by dennisdoomen** [comment]
Yes, I agree with that.

**Comment by arocheleau** [comment]
Now I am facing a dilema for `RaisePropertyChangeFor` and `NotRaisePropertyChangeFor`.  What to expect when invoking one of these 2 functions with a parameter (property name) `null`?  Since `NotRaisePropertyChangeFor` is the opposite of `RaisePropertyChangeFor`, answering to one will answer for the other.

In the case of `RaisePropertyChangedFor`, which `OccurredEvent` should be considered when the parameter given to the function is `null`?  I see 2 possibilities:

1. A `null` property name in a `PropertyChangedEventArgs` means all properties have changed.  So, `RaisePropertyChangeFor(null)`  should return all `OccurredEvent`, which is the same as doing no filtering.
2. The call `RaisePropertyChangeFor(null)` is simply asking to filter the `PropertyChangedEventArgs` the same way we would do with a non-null property name.  Overrall, this call should only consider the `OccurredEvent` targeting a property name of `null` or `string.Empty`.

The difference between the two is how to interpret the `null` value.  Does it have a special meaning saying "all" or "any" properties or it is just a simple value use as-is for filtering?

**Comment by dennisdoomen** [comment]
Unless I misunderstand you, that's already covered by test case `When_an_expected_property_changed_event_was_raised_for_all_properties_it_should_not_throw`

**Comment by arocheleau** [comment]
The test case `When_an_expected_property_changed_event_was_raised_for_all_properties_it_should_not_throw` validates that `RaisePropertyChangeFor(null)` does not throw when a `PropertyChangedEventArgs` is raised with a property name that is `null`.  It does not validate the `IEventRecording` returned by `RaisePropertyChangeFor`.  Right now, the `IEventRecording` returned contains all the `OccurredEvent` not matter the property name provided as parameter to `RaisePropertyChangeFor`.

The current proposal's goal is to filter the `OccurredEvent` considered and returned by `RaisePropertyChangeFor` and keep only those that are related to the specified property name.

In a scenario where these `PropertyChangedEventArgs` are raised and monitored:

1. "SomeProperty"
2. "SomeOtherProperty"
3. null
4. "" (string.Empty)

The call `RaisePropertyChangeFor(x => x.SomeProperty)` is expected to return (1), (3) and (4). (1) because its the target property specified in parameter.  (3) and (4) because a `PropertyChangedEventArgs` with a `PropertyName` of `null` or `string.Empty` means that all properties have changed, which includes `SomeProperty`.

Now, what to expect with the call `RaisePropertyChangeFor(null)`?

1. (1), (2), (3) and (4) because `null` has a special meaning saying the developer is interested in **all** property changes.  The result is identical to what `RaisePropertyChangeFor` returns right now, an unfiltered list of `OccurredEvent`.
2. (3) and (4) because `null` has no special meaning and so `RaisePropertyChangeFor` should only consider the `PropertyChangedEventArgs` that targets a `PropertyName` of `null` or `string.Empty` explicitly.

The choice will have an impact on `NotRaisePropertyChangeFor` as well.  In a scenario where a `PropertyChangedEventArgs` is raised for "SomeProperty" only, `NotRaisePropertyChangeFor(null)` may:

- throw because a property changed was raised and `null` here would expect that no property changed occurred at all.
- do nothing because there was effectively no `PropertyChangedEventArgs` raised with `PropertyName` `null` or `string.Empty`.

**Comment by dennisdoomen** [comment]
> Now, what to expect with the call RaisePropertyChangeFor(null)?

In retrospect it should have thrown since the word `For` implies that you pass in an expression pointing to a specific property.  We should have introduced a `RaisePropertyChange` to cover the scenario where you don't care about the specific property and just want to ensure _some_ property change was raised. However, that would be a breaking change.

So if we want to keep the old behavior, then passing in `null` or empty would return _all_ occurred events.
