### ISSUE TITLE
no generic overloads?

### ISSUE THREAD

**Issue by apobekiaris** [fluentassertions/fluentassertions#412]
it looks really strange to me that there are no overloads for even the simplest assertions so my r# could automatically suggest. Am I missing something? can someone explain?

**Comment by dennisdoomen** [comment]
I'm sorry, but I don't understand what you mean. Care to elaborate?

**Comment by apobekiaris** [comment]
![image](https://cloud.githubusercontent.com/assets/159464/15800862/14d4bb10-2a8e-11e6-9c6f-defbc79bff01.png)


it works for some types but not for others for example look at the above screenshot. I would expect an overload with an argument of ValidationState type but the only overload I get uses an object type.

**Comment by dennisdoomen** [comment]
Ah, that's because the most simple type of assertion possible isn't generic. If I would make that one generic, I wouldn't be able to create more specific assertions for things like `IEnumerable<T>`, `string`, etc. I'm quite bounded by C# limited generic support.

**Comment by apobekiaris** [comment]
IEnumerable for sure are useful however like this it really not safe since
the compiler cannot help and in addition is a big pain to type so much and
not use r#

On Sat, Jun 4, 2016 at 8:13 PM, Dennis Doomen <notifications@github.com>
wrote:

> Ah, that's because the most simple type of assertion possible isn't
> generic. If I would make that one generic, I wouldn't be able to create
> more specific assertions for things like IEnumerable<T>, string, etc. I'm
> quite bounded by C# limited generic support.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dennisdoomen/FluentAssertions/issues/412#issuecomment-223766997>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJu6AFJkoLQVBMaGk7J9p9kDepbmDz_ks5qIbJVgaJpZM4IpbbI>
> .
>



-- 
Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by somewhatabstract** [comment]
Though possible, in order to make `Should` work as `Should<T>`, it would require an extensive change. The `Should<T>` method would need only return a new generic interface like `IAssertOn<T>`, but then all the existing asserters would end up needing to be extension methods of various versions of `IAssertOn<T>`. This is feasible, but a major overhaul of all the FluentAssertions code, and possibly not how the framework was envisaged.

I also don't know if all existing assertions could easily be migrated to such a setup. It certainly feels strange to make such a sweeping change without a really good incentive.

**Comment by dennisdoomen** [comment]
Not going to change that.
