### ISSUE TITLE
Additional GenericDictionaryAssertions

### ISSUE THREAD

**Issue by sbrickey** [fluentassertions/fluentassertions#446]
I found these to be useful:

```
public static void ContainKeyWithValue<TKey, TValue>(this GenericDictionaryAssertions<TKey, TValue> dict, TKey key, TValue value, string because = "", params object[] becauseArgs)
{
    dict.ContainKey(key, because, becauseArgs);
    dict.Subject[key].Should().Be(value, because, becauseArgs);
}

public static void ContainKeyWithValue<TKey, TValue>(this GenericDictionaryAssertions<TKey, TValue> dict, TKey key, Func<TValue, TValue> valueModifier, TValue value, string because = "", params object[] becauseArgs)
{
    dict.ContainKey(key, because, becauseArgs);
    valueModifier(dict.Subject[key]).Should().Be(value, because, becauseArgs);
}
```

benefit being that I can now do this...

```
actual.Should().ContainKeyWithValue("Item1", "a"); // default
actual.Should().ContainKeyWithValue("Item2", v => v.ToLower(), "b"); // using valueModifier
```

yes, it's only a tiny bit of code savings... but the formatting of the assertions is far easier to follow

**Comment by sbrickey** [comment]
note: I suppose the second method (with modifier) should probably contain TModifiedValue, should the modifier return a different type of object... though i start to wonder how much that deviates towards additional ACTions instead of focusing on the ASSERTions.

**Comment by dennisdoomen** [comment]
Looks like a decent improvement. Care to provide me with a PR?

**Comment by sbrickey** [comment]
I'll let someone else take care of that, as well as unit test coverage, naming and other conventions to be consistent with the existing codebase, etc... I just wanted to provide the idea and an example implementation.

**Comment by ben-m-lucas** [comment]
Note that I ended up not implementing the second method that used the valueModifier parameter.  When I was trying to write the failure message for this method, I found that no matter how I wrote the message, it was confusing.  

For example:

a dictionary with {[1, "One"], [2, "Two"]} and the call to ContainKeyWithValue(1, x => x.ToLower(), "two");

has the potential failure message:
Expected dictionary {[1, "One"], [2, "Two"]} to contain [1, "two"], but found [1, "one"]

The language implies that the dictionary should contain [1, "one"] but it doesn't.  The best I could think of was to modify the message as follows:
Expected dictionary {[1, "One"], [2, "Two"]} to contain modified value [1, "two"], but found modified value[1, "one"]

But it began to seem like the messaging was going to obscure what we're really looking for.

I suppose if this type of implementation is important, instead of passing a modifier, we could create a method that takes an IComparer and use that to compare the values.

**Comment by sbrickey** [comment]
only thing left to do now is update the documentation :)

**Comment by ben-m-lucas** [comment]
See comments in PR #508.  The first method had already been implemented, and I'm not sure about the value of the second method as it ends up resulting in confusing messaging when the test fails.  Based on this, I think we should close this issue.

**Comment by jnyrup** [comment]
The second method can be written with (now?) existing methods.

```
var dictionary = new Dictionary<string, string>()
{
    ["key"] = "VaLuE"
};

dictionary.Should().ContainKey("key")
    .WhichValue.Should().BeEquivalentTo("value");
```

**Comment by krajek** [comment]
@sbrickey would you agree that the issue can be closed? It seems that what you requested can be achieved using currently existing functionality.
