### ISSUE TITLE
Suggested Improvement: Using wildcards with "WithMessage" is not intuitive

### ISSUE THREAD

**Issue by gsteinbacher** [fluentassertions/fluentassertions#548]
When using the `ShouldThrow...` and including the `WithMessage`, the ability to use wildcards in the `WithMessage` parameter is not intuitive.  It seems that past versions allowed you to pass a second parameter of `ComparisonMode`.  This seems to be much more clearer since we can see it with intellisense.   

Another simpler solution might be to just add to the documentation that appears in the intellisense popup that wildcards are allowed (and possibly what the wildcards are).

**Comment by dennisdoomen** [comment]
I removed the `ComparisonMode` option because I believe you should never verify the exact details of an exception message. See also point 10 from [this blog post](http://www.continuousimprover.com/2015/11/12-tips-to-write-unit-tests-that-dont.html). Adding some clarification to the name of the argument and documentation is a good idea though.
