### ISSUE TITLE
Ability for custom failure messages?

### ISSUE THREAD

**Issue by faeriedust** [fluentassertions/fluentassertions#552]
I just want to show some debug information in my failure message if the assertion fails..

I came to this library because XUnit dropped support for this, and i heard this library was much better in this regard... which it is for the default messages.. but it seems you can still not do custom ones?

for instance I have an xunit theory right now

```
[Theory, MemberData(nameof(_GetTestWaferData))]
public void WaferInfoFinder_OverValidInput_Succeeds(WaferInfoFinderInput validInput) {
  var containerManager = new CommonTestContainerManager();
  var waferInfoFinder = containerManager.WaferInfoFinder;
  var waferInfo = waferInfoFinder.GetWaferInfo(validInput);

  waferInfo.IsDummy.Should().BeTrue(_DebugString(validInput));

  waferInfo.Warning.Should().BeNullOrEmpty();
}
```

and i just want to display the full information of the input if it fails, so I don't have to try to figure out which input failed..

but the message i get is
"Message: Expected True because LOT_ID: GA05-11161
WAFER_ID: F, but found False."

which makes no sense in English and I'm not sure how to reword it because I can't seem to touch the word "Because" unless I'm missing something?

Is there a better way to do this? Or is this library just for showing the reason why you put the assert and not for showing debug information? :(

**Comment by dennisdoomen** [comment]
Why not use something like:

```
waferInfo.ShouldBeEquivalentTo(new WaferInfo
{
    IsDummy = true,
   Warning = ""
});
```

Then it'll give you all the properties of the `waferInfo` object.

**Comment by faeriedust** [comment]
Hi Dennis, I tried that and it's now trying to enforce that the other 14 properties on WaferInfo are blank, so that isn't quite right either for me.

**Comment by dennisdoomen** [comment]
```
waferInfo.ShouldBeEquivalentTo(new WaferInfo
{
    IsDummy = true,
   Warning = ""
}, options => options.Including(x => x.IsDummy).Including(x => x.Warning));
```

Or just write the original assertion as:

waferInfo.IsDummy.Should().BeTrue($"because {_DebugString(validInput)} is a dummy");

**Comment by faeriedust** [comment]
The first one doesn't tell me anything about the input, which is what i need to see

The second one works reasonably well. :)
I still feel like the library would be much nicer if you could just override the whole message at once.

Oh well, thanks for the help. :)

**Comment by faeriedust** [comment]
I ended up doing this

```
var actual = new {
  IsDummy = waferInfo.IsDummy,
  Warning = waferInfo.Warning
};
var expected = new {
  IsDummy = false,
  Warning = ""
};

actual.ShouldBeEquivalentTo(expected, $"because {_DebugString(validInput)} is valid input");
```

Not i typod before.. IsDummy is supposed to be false lol

**Comment by dennisdoomen** [comment]
So can we close this issue?

**Comment by faeriedust** [comment]
Yeah sure, thanks

**Comment by hichemaichour** [comment]
The proposed solution here is still a work-around, and not a real solution.
I think the library should really enables the modification of the message as we might want something else written.

**Comment by dennisdoomen** [comment]
Maybe, but I don't yet see how that would be possible and what is expected. If you can come up with an example, I can start thinking about a possible solution.

**Comment by hichemaichour** [comment]
so let's say you have a service that returns status and error object. You want to check if status is successful and you want to print the error object.

Currently I get something like:
`Expected object to be Succeeded because {becauseMessage}, but found Failed.`

Adding anything not related to the reason why it should be succeeded makes the part after the comma sound weird:

Ex:
```
Expected object to be Succeeded because creating the service with one node should be possible. Error from service was: Out of memory, but found Failed.
```

Would be better to have it for example:
```
Expected object to be Succeeded because {becauseMessage}, but found Failed.
{ExtraMessage}
```
so that we can add the message we want:

Ex:
```
Expected object to be Succeeded because creating the service with one node should be possible, but found Failed.
Error from service was: Out of memory.
```

As for implementation, you can add an extension `.AddMessage(string message)` to add the extra message we want to show.

**Comment by dennisdoomen** [comment]
Thanks for providing that extensive clarification. An extension method is not going to work since most methods will execute the assertion immediately. Having another parameter is also going to be problematic since the last parameter of most of FA's assertion methods is already a `params object[] becauseArgs`.

**Comment by hichemaichour** [comment]
Emmm, yeah it's hard.
So check this crazy idea that was the only thing I could think of 😆:

Now imagine if the message ends with `.`:
```
Expected value to be 10 because some reason., but found 5.
```
The `.,` looks weird.

So how about this, when the message ends with `.`, instead, it is written in the next line:
```
Expected value to be 10, but found 5.
some reason.
```

Even if the message is actually the because statement, it would still sound good:
```
Expected numbers to contain 4 item(s), but found 3.
we thought we put four items in the collection.
```

**Comment by dennisdoomen** [comment]
Or everything behind the `.` with a space is added to the next line.

**Comment by alexcyoung** [comment]
I've an interest in this general ability (providing a reason for failure as well as a reason why it should succeed). 
Could an error message not be provided as an optional named parameter after the `params object[] becauseArgs`?

**Comment by hichemaichour** [comment]
From [`params` documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params) 
> No additional parameters are permitted after the `params` keyword in a method declaration, and only one `params` keyword is permitted in a method declaration.

**Comment by alexcyoung** [comment]
Good point @hichemaichour, my bad.
So going back to your idea of passing in the error message using the "." this would just be convention? e.g.
`variable.Should().BeTrue("because truth is good. Reason for it not being true is etc")`

Am I understanding you correctly?

**Comment by hichemaichour** [comment]
Nope, I gave [example here](https://github.com/fluentassertions/fluentassertions/issues/552#issuecomment-519194831)

> So how about this, when the message ends with `.`, instead, it is written in the next line:
> 
> ```
> Expected value to be 10, but found 5.
> some reason.
> ```

The example you wrote would fail if for example you have this:
```
eatApple.Should().BeTrue("because my Dr. said I should do")
```
which would translate to:
```
Expected eatApple to be true because my Dr, but found false.
said I should do
```

**Comment by cherchezlafemme** [comment]
Having the ability to tag a message would be super useful. The error shows up in Jenkins logs, and being able to pass say a content of the response that has some error details will enable fast debugging. 
In ideal world we would have `response.StatusCode.Should().Be(HttpStatusCode.NotFound).AddMessage("Response content: " +  await response.Content.ReadAsStringAsync() )` while right now we are using the "because" part to log in the response.content which is a hack and doesn't read as English :/

**Comment by cherchezlafemme** [comment]
I really like the idea of @hichemaichour "As for implementation, you can add an extension .AddMessage(string message) to add the extra message we want to show."

**Comment by hichemaichour** [comment]
> I really like the idea of @hichemaichour "As for implementation, you can add an extension .AddMessage(string message) to add the extra message we want to show."

@cherchezlafemme , sadly it doesn't work because as @dennisdoomen [said](https://github.com/fluentassertions/fluentassertions/issues/552#issuecomment-518552682):

> An extension method is not going to work since most methods will execute the assertion immediately. Having another parameter is also going to be problematic since the last parameter of most of FA's assertion methods is already a `params object[] becauseArgs`.

**Comment by hichemaichour** [comment]
However, the idea of having tags could be useful, but they would be added to `should()` => `should(IDictionary<string, object> tags = null)`

**Comment by dennisdoomen** [comment]
I won't look very fluent unfortunately

**Comment by hichemaichour** [comment]
`should().BeTrue("because the sky is high", withTags: tags)` 🤔

**Comment by dennisdoomen** [comment]
@faeriedust you could also use the following construct:

using (new AssertionScope(_DebugString(validInput)))
{
   waferInfo.IsDummy.Should().BeTrue();
}

**Comment by kartikdeepsagar** [comment]
@dennisdoomen It will be good if we can provide a fully customized error message without an existing error message

**Comment by fractalocity** [comment]
Hacked because being forced to use fluentassertions when NUnit assert worked great. 
Who the blank-a-de-blank wants to know the 'Why' to the expected value? Grates on my nerves so much. Most people want to know why something is wrong, not why something is right. 

Let's say 'm in class and the teacher asks a question. Let's say they asked what 2*5 was. If I said 10 ... .... I'm not going to ask why. I'm not going to ask Why I got the correct answer. However, if I said 8 and the teacher said no ... I might ask why 8 is the wrong answer. NO ONE WANTS TO KNOW why the correct answer is the correct answer. 
So this, 
eatApple.Should().BeTrue("because my Dr. said I should do") ... I already know why I should eat an apple. If 'eatApple == false' ... then I would be asking whaaattttt???? WHY? BECAUSE. I don't care why something is true, i want to know why somethign went wrong. Who the heck is telling me eatApple is false??? What code above my Should().BeTrue() is lying to me. I already know to eat the freaking apple. I want to know what is going on if my code tells me to not eat the apple. 
After I was forced to convert to fluentassertions our failure statements are so jacked up. Not exactly ticked off at fluentassertions ... just the dip whit forcing us to use this stuff.

**Comment by dennisdoomen** [comment]
@fractalocity Thank you for sharing your insights 😜

I don't where your frustrations are coming from exactly, but that "because" option is, well, optional. I only use it occasionally when I think it _adds_ clarity to the outcome. No need to be dogmatic about it.

**Comment by fractalocity** [comment]
@sskfny  I agree x 1000 and then some. I cannot comprehend why the sentence structure is output as it currently is. I was expecting something like you were expecting too. You have a valid question and expectation. But it hasn't changed in two years+, so I wouldn't expect it to change now. Fluentassertions make the code a lot more readable, but not the output error message. I don't understand when then sentence structure, "_Expected boolean not to be False because Something failed arguments wrong, but found False._", would/could ever be a considered normal sentence structure. But again, really good for making code a lot easier to read.

**Comment by dennisdoomen** [comment]
The _but found false_ is a bit unnecessary indeed. I'd welcome a PR to change that.

**Comment by fractalocity** [comment]
Thanks @dennisdoomen. 
You said you might remove the 'but found false' at the end of the sentence. However, it is nice to know, 'Expected to be false, but found true'. It is nice to know what the answer is supposed to be as well as what the test found instead. It might not be a bad idea to just move the 'something Failed arguments wrong' to come after 'but found False', like @sskfny suggested. This is just my opinion. Others might have a different opinion/suggestion.

**Comment by sskfny** [comment]
Should a new issue or enhancement request to be raised ?

**Comment by dennisdoomen** [comment]
> Should a new issue or enhancement request to be raised ?

If you're going to be doing the work, then no.

**Comment by sskfny** [comment]
I can give it a go, assuming the below structure is okay. Was studying the code so basically {reason} in the FailWith in various places need to be positioned properly.

or if any other suggestion let me know

Expected boolean not be False, but found False.
Something Failed arguments wrong

**Comment by dennisdoomen** [comment]
Please create a new issue that captures the proposal first.
