### ISSUE TITLE
ShouldAllBeEquivalentTo for Ienumerable<T> does not fail if Ienumberable<T> is empty list

### ISSUE THREAD

**Issue by daniellehollman** [fluentassertions/fluentassertions#565]
I illustrated the bug with 2 tests, the first should succeed and the second should fail. 
However the second test also succeeds. 

        [TestMethod]
        public void ListWithData_ShouldPass()
        {
            IEnumerable<int> expected = new List<int>() {1};
            IEnumerable<int> actual = new List<int>() { 1  };

            actual.ShouldAllBeEquivalentTo(expected);
        }

        [TestMethod]
        public void ListWithoutData_ShouldFail()
        {
            int expected =  1;
            IEnumerable<int> actual = new List<int>() { };

            actual.ShouldAllBeEquivalentTo(expected); //actual.ShouldAllBeEquivalentTo should fail, but doesn't
           Assert.AreEqual(expected, actual.Single()); //Assert.AreEqual fails, which is the expected behaviour 
        }

**Comment by dennisdoomen** [comment]
Good catch. Thanks for reporting.

**Comment by kwlin** [comment]
The issue on the second unittest is not the empty list but more about different types. The unittest is verifying an int value with a IEnumerable<int> value. 

The expected behaviour of the ShouldAllBeEquivalentTo extensions method should throw an exception or assertion error when the actual type and expected type are not the same. 

For verify'ing the content of the collection, @daniellehollman  should use actual.Should(). contruction and not ShouldAllBeEquivalentTo.

**Comment by dennisdoomen** [comment]
Actually, the second test is supposed to assert that all items in `actual` are equivalent to `1`. But the edge case here is that *actual* is empty.

**Comment by kwlin** [comment]
@dennisdoomen: Ah, I see. It wasn't very clear to me in the documentation (http://fluentassertions.com/documentation.html#collections-and-dictionaries).

**Comment by dennisdoomen** [comment]
This confusion is going to be fixed in 5.0. Will close this issue.
