### ISSUE TITLE
Support for IReadOnlyDictionary, IReadOnlyCollection

### ISSUE THREAD

**Issue by shatl** [fluentassertions/fluentassertions#568]
Please add assertions support for IReadOnlyDictionary, IReadOnlyCollection, etc..

**Comment by dennisdoomen** [comment]
What would that mean? They both implement `IEnumerable<T>` and `IDictionary<TKey, TValue>` for which we already have plenty of extensions.

**Comment by jnyrup** [comment]
`IReadonlyDictionary<TKey, TValue>` does not implement `IDictionary<TKey, TValue>`, it implements `IReadOnlyCollection<T>` and `IEnumerable<T>`.

`Dictionary<TKey, TValue>` on the other hand implements both `IReadonlyDictionary<TKey, TValue>` and `IDictionary<TKey, TValue>`.

**Comment by dennisdoomen** [comment]
Hmm. Didn't realize this.

**Comment by dennisdoomen** [comment]
Hmm. Didn't realize this.

**Comment by SaroTasciyan** [comment]
Assuming that we are talking about generics, they both implement `IEnumerable<T>` which results in `Should()` call returning an instance of `GenericCollectionAssertions<T>` for both. One would expect to have something similar to `GenericDictionaryAssertions<T>` be returned for `IReadyOnlyDictionary<T>` (actually the implementation to support the existing functionality should be the same since the only difference is the lack of add remove methods which is already not being used)

However, I think we already have all the functionality required for `IReadonlyCollection<T>` since it operates on `IEnumerable<T>` . What else is requested?

**Comment by PavelRusin** [comment]
@SaroTasciyan methods like `ContainKey` are missing for `IReadOnlyDictionary<T>`. As a workaround people write `readOnlyDictionary.ContainsKey(variant.Key).Should().BeTrue()` but then lose the benefits of a clear assertion message.

**Comment by krajek** [comment]
It is being implemented in #710

**Comment by krajek** [comment]
@jnyrup maybe let's close this "old" issue and focus on the current attempts to support read-only dictionaries?
BTW I didn't realize it was already more than 2 years since the discussion started ...

**Comment by dennisdoomen** [comment]
Let's keep it open until we've been able to make a decision on the most suitable implementation.
