### ISSUE TITLE
And.BeEquivalentTo vs ShouldBeEquivalentTo

### ISSUE THREAD

**Issue by Mardoxx** [fluentassertions/fluentassertions#708]
```cs
public class A
{
    public string a { get; set; }
}

var actual = new List<A>
{
    new A
    {
        a = "a"
    }
};

var expected = new List<A>
{
    new A
    {
        a = "a"
    }
};

//works
actual.ShouldBeEquivalentTo(expected);

//fails
actual.Should().NotBeNull()
    .And.NotBeEmpty()
    .And.HaveCount(1)
    .And.BeEquivalentTo(expected);
```

Cheers.

**Comment by dennisdoomen** [comment]
Because in 4.x, `BeEquivalentTo` is something else than `ShouldBeEquivalentTo`. In 5.x, we've unified that API/

**Comment by Mardoxx** [comment]
Not following, your [docs say](http://fluentassertions.com/documentation.html#collections) that the failing method should work -- or have I missed something?

**Comment by dennisdoomen** [comment]
Yes, but the difference is that `BeEquivalentTo` relies on the `Equals` implementation of the objects in the collection. `ShouldBeEquivalentTo` uses a deep object comparison which is highly customizable. Because of this complexity, in the [first beta](https://github.com/fluentassertions/fluentassertions/releases/tag/5.0.0-beta.1) of 5.0 `BeEquivalentTo` has been re-implemented using the logic of `ShouldBeEquivalentTo` and the latter no longer exists.

**Comment by Mardoxx** [comment]
Ah great, thanks! I was just typing out that I notice the example uses a list of primitives so in that respect, it does make sense that it should fail here!
