### ISSUE TITLE
VSTS build error: Index source information could not be retrieved.

### ISSUE THREAD

**Issue by devjohnny** [fluentassertions/fluentassertions#767]
**Issue Summary**
I've got a C# web application and this application uses the FluentAssertions from nuget. Build is happening online via VSTS (Visual Studio 2015 build agent). Everything compiles ok, but the build throws an error getting symbol indexes from FluentAssertions.pdb. Error as follows:

Indexed source information could not be retrieved from 'd:\x\y\z\<ProjectName>\bin\FluentAssertions.pdb'. Symbol indexes could not be retrieved.

Running symchk I get the same error, so perhaps it's the same cause.

Steps to Reproduce
Add deps to MVC or asp.net WebApi project, build and publish symbols on TFS
Project compiles but build throws error.

**Technical details:**
package id="FluentAssertions" version="5.1.1" targetFramework="net452"
.NET Version: 4.5.2

**Comment by dennisdoomen** [comment]
Hi @devjohnny. Thanks for reporting this. 

What _specifically_ is the build doing there? If it is running unit tests, can you share the entire stack trace?

**Comment by devjohnny** [comment]
I use it in a unit test project and the build is working properly and all unit tests are passed. After the build phase I have a 'Publish Symbols' step and I get the error: 

> _Indexed source information could not be retrieved from d:\x\1234\5678\bin\FluentAssertions.pdb. Error: Symbol indexes could not be retrieved._

If I rollback to v4.19, it is working properly. I checked the v4.19 pdb and v5.11 with symchk and I get the error only the v5.1.1

**Comment by jnyrup** [comment]
Reading from other [issues](https://github.com/JoshClose/CsvHelper/issues/535), the problem seems to be:
* The default value for `<DebugType>` is `portable` - the new [portable PDB](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md).
* TFS 2017 [can't read](https://developercommunity.visualstudio.com/content/problem/33776/indexed-source-information-could-not-be-retrieved-1.html) the new portable PDB format.
* On the other hand, VS code only [support portable PDBs](https://developercommunity.visualstudio.com/content/problem/33776/indexed-source-information-could-not-be-retrieved-1.html).

Some possible workarounds for consumers of Fluent Assertions:
* upgrade to TFS 2018
* exclude `FluentAssertions.pdb` when publishing symbols
* Build Fluent Assertions from source and select the `<DebugType>` that suits you

What did others do?
[Moq](https://github.com/moq/moq4/issues/428) selected `full` `<DebugType`.
[NodaTime](https://github.com/nodatime/nodatime/issues/972) chose to stay with `portable`.

**Comment by dennisdoomen** [comment]
Why would you publish symbols of a unit test project??

**Comment by devjohnny** [comment]
The solution contains several class libraries and unit test projects so it isn't a single unit test solution.

I will try the recommendation above.

Thank you guys.
