### ISSUE TITLE
Invoking should support Func<TInput, TResult>

### ISSUE THREAD

**Issue by benjamin-bader** [fluentassertions/fluentassertions#872]
### Description

Properties are merely functions in disguise, and it would be useful to be able to assert on exceptions that they might throw, for example that accessing a property of a disposed object throws an `ObjectDisposedException`.

This doesn't work today because a simple lambda that accesses a property is compiled as a `Func<TInput, TResult>`, but there is no corresponding overload that can accept this delegate type.

### Complete minimal example reproducing the issue

```csharp

class MyDisposable : IDisposable
{
  // the usual Disposable implementation elided here

  bool IsConnected
  {
    get
    {
      if (disposed) throw new ObjectDisposedException(GetType().Name);
      return _isConnected;
    }
  }
}

// Arrange
var subject = new MyDisposable();

// Act
subject.Dispose();

// Assert
subject.Invoking(it => it.IsConnected).Should().Throw<ObjectDisposedException>();
```

### Expected behavior:

I would expect this to invoke the lambda, and verify that the specified exception was thrown.

### Actual behavior:

Compilation failure.

### Versions

Using FluentAssertions 5.4.1, running on .NET Core 2.0

**Comment by benjamin-bader** [comment]
I have an extension method in my project to accomplish this which is very simple.  If there's agreement that this is a reasonable approach, and that this is a desirable feature, then I'd be happy to make a PR with this, tests, and documentation updates.

```csharp
public static Action Invoking<TSubject, TResult>(this TSubject subject, Func<TSubject, TResult> func)
{
    return () => func(subject);
}
```

**Comment by dennisdoomen** [comment]
You're not really _invoking_ a property. You're _reading_ it, or _getting_ it. Isn't it?

**Comment by benjamin-bader** [comment]
You're correct, of course, but to me it seems a distinction without a difference.  A property, whether `invoked` or `read`, is still (potentially) custom code that is executed.

Do you think this would be better were it named `Getting` (or `Accessing` or `Reading`)?  I think that it would certainly read better, but I wonder whether it would be obvious what the method is used for.  Or why it would appear to act as a superset of `Invoking`.  What do you think?

**Comment by krajek** [comment]
I like this feature, I would certainly use it myself. 👍 
@dennisdoomen Can we settle on `Getting` and move on to implementation?

**Comment by dennisdoomen** [comment]
Yep. I like that one as well.

**Comment by jnyrup** [comment]
The proposed function signature is more general than for only properties.
Which is why I dislike naming it `Getting`, as it only *might* be property read.

To use the feature, one would have to write
```c#
subject.Getting(x => x.ComputeExpensiveValue())
```

even though you aren't just *Getting* a value, as in returning the value of a backing field.

For this to be really good, I'd like the method to return a `Func<TResult>` instead of an `Action` and deliver it together with a solution to #422, such that one can write either of:
```
Func<string> func = () => subject.StringProperty;
func.Should().NotThrow()
    .Which.Should().Be("expectedValue")

subject.Invoking(x => e.StringProperty).Should().NotThrow()
    .Which.Should().Be("expectedValue")
```

**Comment by dennisdoomen** [comment]
Hmm, I don't entirely get your objections here. We could even use that to enhance the code that tries to detect the name of the property and set the `context`

**Comment by jnyrup** [comment]
As I understand the notation of `Get` it is mainly intended for getters, such as properties that only returns the value of the underlying backing field or methods that does very little computation.
For other scenarios, e.g. IO operations, `Find` or `Load` might be more proper prefixes.

`Func<T, TResult>` can match a property, where `Getting` would be a fine name, but it also matches many other cases, where the semantics mismatches.

That's why I dislike `Getting` since it imposed semantics we know nothing about.

**Comment by dennisdoomen** [comment]
Alright, it seems that `Invoking` is the best option considering the various situations we need to cover.

**Comment by jnyrup** [comment]
We're also missing a similar result returning overload for `Task`.

```c#
public static Func<Task<TResult>> Awaiting<T, TResult>(this T subject, Func<T, Task<TResult>> action)
{
    return () => action(subject);
}```
